# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58961fc084f61560ef52eceb1b09446d5a6a49d7d07b24189801f62d58f2621c876db46f8096385163dfc8cc77d5975a76d8617fdae4125af97cdc44a5472c33

test:
  secret_key_base: fdfb8ab94b79e9fc4eab2041a48153615b2b3f8ad47929c56c4f40e112ccf9af1943566d6da4cb39e949f419ce4200ec2438a30ccd62bd4bb02090f004f4bb1d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
